### PR TITLE
First test of the new tritech track reader

### PR DESCRIPTION
**Pull request by OniDaito**
Hello there.
I'm a new member of SMRU and I'm working on some software here at St Andrews. A few folks wanted to read some track files in R so I wrote an additional bit of code here that might work for them. If you have the time, do please have a look at this pull request and see if it's good enough to pull into your codebase.
Cheers
Ben

### CODE REVIEW

**Comment by TaikiSan21** [comment]
Hi Ben!
A quick question about your comment in "readPamData.R" - are you basing this on the Matlab files in this repo? I'm afraid these are pretty out of date - I only downloaded them when this project first started, but I haven't bothered to keep them up to date with changes. The most up-to-date files from the Pamguard folks can be found [here](https://github.com/PAMGuard/PAMGuardMatlab), and they include the !isBackground check. 

In any case, I was able to read in the GTD.pgdf file you included with my original version of readPamData. If you can send me a file where the original readPamData doesn't work I'd like to take a look and see why it is happening.

**Comment by OniDaito** [comment]
Hello there. Thanks for the reply.
I was indeed basing the R code from the MATLAB version. I will double check which version I was using. It could be I was also looking at the recent Java codebase too (I've been working in 4 languages for the past couple of works so it tends to blur). For whatever reason, the GTD.pgdf I included failed the check. I don't think that file has the correct type information set. It was the data$identifier == fileInfo$objectType line.

I'll check over this again, redo the comments and double check that this file indeed doesn't have the correct identifier. It might be that the problem is actually in the file creation somewhere else in PAMGuard.
Cheers
Ben

**Comment by OniDaito** [comment]
Hello again,
The problem I'm getting is something to do with this line:

data$identifier 

I'm getting NULL for this when using the GTD.pgdf 
I've had a look and it should be -1 in this field and not null. Not sure why it's not being set properly. It could be the file itself as I can't see anything in the code that would cause it. Odd.

**Comment by TaikiSan21** [comment]
Not quite sure what is happening here, when I process the GTD.pgdf file you have uploaded here the `data$identifier` is always equal to 0. I also don't encounter any issues if I comment out the `if (fileInfo$fileHeader$moduleType != 'Gemini Threshold Detector')` line that you had added. No idea why we are seeing different results with what should be the same file.

**Pull request closed without merging**
